name: Windows Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSYS2 / MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-libuv
            mingw-w64-x86_64-pkg-config
      - name: Debug MSYS2 Path
        shell: msys2 {0}
        run: |
          # This should output the directories where the shell looks for commands
          echo $PATH
          # Check if make is installed and where it is located
          which make
      - name: Compile Espresso server and tests
        run: |
          C:\msys64\usr\bin\bash.exe -lc "make"

      - name: Run Unit Tests
        run: |
          C:\msys64\usr\bin\bash.exe -lc "make test_unit"

      - name: Run Integration Tests
        run: |
          C:\msys64\usr\bin\bash.exe -lc "make test_integration"
